MODULES += os/lib/cbor
MODULES += os/net/security/cose
MODULES += os/net/security/sha
MODULES += os/net/app-layer/coap
MODULEDIRS += $(CONTIKI)/os/net/security/micro-ecc
MODULES_SOURCES += uECC.c

ifneq ($(MAKE_EDHOC_METHOD),)
  CFLAGS += -DEDHOC_METHOD=$(MAKE_EDHOC_METHOD)
endif

ifeq ($(TARGET), zoul)
  CFLAGS += -DuECC=1
else
  CFLAGS += -DuECC=0
endif
